### ISSUE TITLE
missing contact

### ISSUE THREAD

**Issue by KoreTeknology** [david-c14/SubmarineUtility#16]
Hi David, i may be wrong to contact you here, but after looking for an email or other sort of messenger, i didnt find you... how can we have a talk.. i am a VCV module dev and Ui designer.. i may have few questions regarding your modules and updates... 
thank you very much if you decide to answer me, cheers
have a great day

uriel

**Comment by david-c14** [comment]
I've pm'd you through the official vcv rack forum.
