### ISSUE TITLE
Slightly weird graphics

### ISSUE THREAD

**Issue by lnikj** [david-c14/SubmarineUtility#4]
Hi David

A minor thing with the second beta:

When I first open it, it looks like this:
<img width="104" alt="screenshot_39" src="https://user-images.githubusercontent.com/24451110/45174610-38a84d00-b203-11e8-9d7b-e65787c7b950.png">
Once I click on it, it does this:
<img width="163" alt="screenshot_41" src="https://user-images.githubusercontent.com/24451110/45174639-4a89f000-b203-11e8-8e20-e3e1f5058143.png">
Once I close the accordion and reopen, it looks like this:
<img width="313" alt="screenshot_40" src="https://user-images.githubusercontent.com/24451110/45174662-58d80c00-b203-11e8-83c5-85525e2e3820.png">

Not sure that the first version did.

Cheers

Nik

**Comment by david-c14** [comment]
It does look weird. I'll try to look at it tomorrow. Is that the beta2 from today? On Mac?

**Comment by lnikj** [comment]
Sorry, should have said. Yes to both. (10.13.6).

**Comment by lnikj** [comment]
My apologies David. This graphics glitch is NOT present in the second beta. I did a 'make install' but have just noticed that this copied the .zip to my plugins directory but did not unzuo it over the top of the existing copy. So, the problem is there in the first beta but gone in the second.

**Comment by lnikj** [comment]
Here's a Mac build of the second beta:
[SubmarineUtility-0.6.0Beta2-mac.zip](https://github.com/david-c14/SubmarineUtility/files/2359626/SubmarineUtility-0.6.0Beta2-mac.zip)
