### ISSUE TITLE
Plugs in wrong order

### ISSUE THREAD

**Issue by SmallTownSound** [david-c14/SubmarineUtility#7]
The plugins are not alphabetizing properly.  Using v 6.1

**Comment by david-c14** [comment]
I have not attempted to alphabetize them. That is actually a very hard thing to do in a multicultural world. 

However, I will label this as a feature request and see if I can improve on it.

**Comment by david-c14** [comment]
I have at least made the sorting case-insensitive for authors. This is probably the best I can do at this stage unless I bring in the IBM ICU library, and it matches the sorting that Andrew does.

This is in 0.6.2
