### ISSUE TITLE
scrolling

### ISSUE THREAD

**Issue by wimwijn01** [david-c14/SubmarineUtility#9]
Is it possible to make it scroll with the mousewheel when you hover with the mouse over the module

**Comment by david-c14** [comment]
I'm not sure that it is.

I keep looking into it. But I haven't found a way.

Part of me thinks that if it was possible, other people would have made their knobs respond to the mouse-wheel and as far as I can see no-one has. There was a dicussion about that on the issues page for vcv-rack itself.

**Comment by david-c14** [comment]
I don't believe this is acheivable
